version: "3.8"

networks:
  symfony_sertificate_net:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT-80}:80"
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ./src:/srv/current/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - symfony_sertificate_net

  app:
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        user: $USER_PHP
        uid: $UID
        php_version: $PHP_VERSION
    volumes:
      - ./src:/srv/current/
    container_name: ${PROJECT_NAME}_app
    networks:
      - symfony_sertificate_net
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: ${PROJECT_NAME}_db
    environment:
      PGDATA: /var/lib/postgresql/data/db-files/
      POSTGRES_DB: sertificate
      POSTGRES_USER: www
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - symfony_sertificate_net